volumes:
  dockovpn_data:
name: 'vpn'
services:
  dockovpn:
    container_name: dockovpn
    image: alekslitvinenk/openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "80:8080/tcp"
    network_mode: host
    environment:
      - HOST_ADDR=${HOST_ADDR:-$(curl -s https://api.ipify.org)}
    volumes:
        - dockovpn_data:/opt/Dockovpn_data
