name: 'srv'
services:
  dozzle-agent:
    container_name: dozzle-agent
    restart: unless-stopped
    image: amir20/dozzle:latest
    command: agent
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - DOZZLE_HOSTNAME=10.111.17.42
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9008:7007
