volumes:
  gitea-data:
  gitea-config:
  postgres:
name: 'srv'
services:
  gitea:
    container_name: gitea
    restart: always
    image: docker.gitea.com/gitea:1.23.7-rootless
    ports:
      - "3000:3000"
      - "2222:2222"
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=postgres
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
      - GITEA__server__ROOT_URL=http://127.0.0.1:3000
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 2048M
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - PGUSER=postgres
      - PGPORT=${CONFIG_POSTGRESQL_PORT:-5432}
      - POSTGRES_DB=${CONFIG_POSTGRESQL_NAME:-postgres}
      - POSTGRES_PASSWORD=${CONFIG_POSTGRESQL_PASSWORD:-postgres}
      - POSTGRES_USER=${CONFIG_POSTGRESQL_USER:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 832M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
