volumes:
  jenkins_home:
name: 'srv'
services:
  jenkins-agent:
    restart: always
    container_name: jenkins_agent
    image: jenkins/inbound-agent:jdk17
    privileged: true
    init: true
    user: root
    environment:
      - JENKINS_URL=http://10.111.17.41:8080
      - JENKINS_SECRET=XXXXXXXX
      - JENKINS_AGENT_NAME=10.111.17.41
      - JENKINS_AGENT_WORKDIR="/var/jenkins_home"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
