volumes:
  nginx_data:
  nginx_ssl:
name: 'srv'
services:
  nginx:
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - nginx_ssl:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: 128M
  logs:
    container_name: nginx-proxy-logs
    image: busybox:latest
    restart: unless-stopped
    volumes:
      - nginx_data:/data
    command:
      - sh 
      - -c 
      - "tail -f /data/logs/*.log"
    network_mode: none
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 32M
