volumes:
  nginx_proxy:
services:
  nginx:
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_proxy:/data
      - nginx_proxy:/etc/letsencrypt
  logs:
    container_name: nginx-proxy-logs
    image: busybox:latest
    restart: unless-stopped
    volumes:
      - nginx_proxy:/data
    command:
      - sh 
      - -c 
      - "/data/logs/*.log"
    network_mode: none
