volumes:
  oracle_data:
#  oracle_backup:
name: 'srv'
services:
  oracle:
    container_name: oracle
    #image: container-registry.oracle.com/database/free:latest # It supports up to 2 CPUs and 20 GB of user data
    image: container-registry.oracle.com/database/express:latest # a maximum of 2 GB of user data and a limit of CPUs
    environment:
      - ORACLE_SID=XE #FREE
      #- ORACLE_PDB=XEPDB1 # ORCLPDB1
      - ORACLE_PWD=Oracle_123 # default user: system
    ports:
      - 1521:1521
    volumes:
      - oracle_data:/opt/oracle/oradata
      #- oracle_backup:/opt/oracle/backup
