volumes:
  postgres:
name: 'srv'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - PGPORT=${CONFIG_POSTGRESQL_PORT:-5432}
      - POSTGRES_DB=${CONFIG_POSTGRESQL_NAME:-postgres}
      - POSTGRES_PASSWORD=${CONFIG_POSTGRESQL_PASSWORD:-postgres}
      - POSTGRES_USER=${CONFIG_POSTGRESQL_USER:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
